spring.application.name=Spring_Back_end

spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_system
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Debug mode
#debug=true

#a modifier apres pour creer une class independament
#spring.main.allow-circular-references=true
#server.port=8081


# D�finir la limite de taille pour les fichiers upload�s
#spring.servlet.multipart.max-file-size=2MB
#spring.servlet.multipart.max-request-size=2MB
